/**
 * 旅程タイムライン（日別スケジュール）ライブラリ
 *
 * - フライト・ホテルのチェックイン/アウトを自動配置
 * - ユーザーが観光・食事の予定を追加
 * - 日ごとのタイムライン表示
 * - AsyncStorage でローカル保存
 */

import AsyncStorage from '@react-native-async-storage/async-storage';

// ===== 型定義 =====

export type TimelineEventType =
  | 'flight_departure'
  | 'flight_arrival'
  | 'hotel_checkin'
  | 'hotel_checkout'
  | 'sightseeing'
  | 'restaurant'
  | 'shopping'
  | 'activity'
  | 'transport'
  | 'free_time'
  | 'custom';

export interface TimelineEvent {
  id: string;
  tripId: string;
  date: string;              // YYYY-MM-DD
  time: string;              // HH:mm（24h）
  endTime?: string;          // HH:mm（終了時刻、任意）
  type: TimelineEventType;
  title: string;
  subtitle?: string;         // 補足情報
  location?: string;         // 場所名
  address?: string;          // 住所
  note?: string;             // メモ
  guideKey?: string;         // 紐づけた観光ガイドのキー（例: 'DE:frankfurt'）
  isAutoGenerated: boolean;  // フライト/ホテルから自動生成
  sourceId?: string;         // 元のフライトID or ホテルID
  completed: boolean;
}

export interface DaySchedule {
  date: string;              // YYYY-MM-DD
  dayNumber: number;         // 旅行の何日目か（1始まり）
  dayLabel: string;          // "Day 1" や "1日目"
  events: TimelineEvent[];
}

// ===== イベントタイプの表示設定 =====

export const EVENT_TYPE_CONFIG: Record<TimelineEventType, {
  emoji: string;
  label: string;
  color: string;
  bgColor: string;
}> = {
  flight_departure:  { emoji: '🛫', label: '出発', color: '#2563EB', bgColor: '#EFF6FF' },
  flight_arrival:    { emoji: '🛬', label: '到着', color: '#2563EB', bgColor: '#EFF6FF' },
  hotel_checkin:     { emoji: '🏨', label: 'チェックイン', color: '#7C3AED', bgColor: '#F5F3FF' },
  hotel_checkout:    { emoji: '🏨', label: 'チェックアウト', color: '#7C3AED', bgColor: '#F5F3FF' },
  sightseeing:       { emoji: '📸', label: '観光', color: '#059669', bgColor: '#ECFDF5' },
  restaurant:        { emoji: '🍽️', label: '食事', color: '#D97706', bgColor: '#FFFBEB' },
  shopping:          { emoji: '🛍️', label: 'ショッピング', color: '#DB2777', bgColor: '#FDF2F8' },
  activity:          { emoji: '🎯', label: 'アクティビティ', color: '#0891B2', bgColor: '#ECFEFF' },
  transport:         { emoji: '🚕', label: '移動', color: '#6B7280', bgColor: '#F3F4F6' },
  free_time:         { emoji: '☕', label: 'フリータイム', color: '#78716C', bgColor: '#FAFAF9' },
  custom:            { emoji: '📌', label: 'その他', color: '#4B5563', bgColor: '#F9FAFB' },
};

// ===== フライト・ホテルから自動イベント生成 =====

interface FlightData {
  id: string;
  airline: string;
  flight_number?: string;
  departure_airport: string;
  arrival_airport: string;
  departure_time: string;    // ISO 8601
  arrival_time?: string;     // ISO 8601
}

interface HotelData {
  id: string;
  name: string;
  checkin_date: string;      // YYYY-MM-DD
  checkout_date: string;     // YYYY-MM-DD
  checkin_time?: string;     // HH:mm
  checkout_time?: string;    // HH:mm
  address?: string;
}

/**
 * フライト情報からタイムラインイベントを生成
 */
export function generateFlightEvents(tripId: string, flights: FlightData[]): TimelineEvent[] {
  const events: TimelineEvent[] = [];

  for (const flight of flights) {
    if (!flight.departure_time) continue; // 出発日時未設定のフライトはスキップ
    const depDate = flight.departure_time.slice(0, 10);
    const depTime = flight.departure_time.slice(11, 16) || '00:00';
    const flightLabel = flight.flight_number
      ? `${(flight.airline||'')} ${flight.flight_number}`
      : (flight.airline||'未設定');

    events.push({
      id: `auto_dep_${flight.id}`,
      tripId,
      date: depDate,
      time: depTime,
      type: 'flight_departure',
      title: `${flightLabel} 出発`,
      subtitle: `${flight.departure_airport||'---'} → ${flight.arrival_airport||'---'}`,
      location: flight.departure_airport||'',
      isAutoGenerated: true,
      sourceId: flight.id,
      completed: false,
    });

    if (flight.arrival_time) {
      const arrDate = flight.arrival_time.slice(0, 10);
      const arrTime = flight.arrival_time.slice(11, 16) || '00:00';

      events.push({
        id: `auto_arr_${flight.id}`,
        tripId,
        date: arrDate,
        time: arrTime,
        type: 'flight_arrival',
        title: `${flightLabel} 到着`,
        subtitle: `${flight.departure_airport} → ${flight.arrival_airport}`,
        location: flight.arrival_airport,
        isAutoGenerated: true,
        sourceId: flight.id,
        completed: false,
      });
    }
  }

  return events;
}

/**
 * ホテル情報からタイムラインイベントを生成
 */
export function generateHotelEvents(tripId: string, hotels: HotelData[]): TimelineEvent[] {
  const events: TimelineEvent[] = [];

  for (const hotel of hotels) {
    // チェックイン
    events.push({
      id: `auto_ci_${hotel.id}`,
      tripId,
      date: hotel.checkin_date,
      time: hotel.checkin_time || '15:00',  // デフォルト15時
      type: 'hotel_checkin',
      title: `${hotel.name} チェックイン`,
      location: hotel.name,
      address: hotel.address,
      isAutoGenerated: true,
      sourceId: hotel.id,
      completed: false,
    });

    // チェックアウト
    events.push({
      id: `auto_co_${hotel.id}`,
      tripId,
      date: hotel.checkout_date,
      time: hotel.checkout_time || '11:00', // デフォルト11時
      type: 'hotel_checkout',
      title: `${hotel.name} チェックアウト`,
      location: hotel.name,
      address: hotel.address,
      isAutoGenerated: true,
      sourceId: hotel.id,
      completed: false,
    });
  }

  return events;
}

// ===== 日別スケジュール生成 =====

/**
 * 旅行期間の日付リストを生成
 */
function getDateRange(startDate: string, endDate: string): string[] {
  const dates: string[] = [];
  const current = new Date(startDate);
  const end = new Date(endDate);

  while (current <= end) {
    dates.push(current.toISOString().slice(0, 10));
    current.setDate(current.getDate() + 1);
  }

  return dates;
}

/**
 * 全イベントを日別にグルーピングし、タイムライン順にソート
 */
export function buildDaySchedules(
  departureDate: string,
  returnDate: string | null | undefined,
  autoEvents: TimelineEvent[],
  customEvents: TimelineEvent[],
): DaySchedule[] {
  const allEvents = [...autoEvents, ...customEvents];
  // return_dateがnullの場合はdepartureDateのみ（日帰り扱い）
  const effectiveReturn = returnDate || departureDate;
  const dates = getDateRange(departureDate, effectiveReturn);

  return dates.map((date, index) => {
    const dayEvents = allEvents
      .filter(e => e.date === date)
      .sort((a, b) => a.time.localeCompare(b.time));

    return {
      date,
      dayNumber: index + 1,
      dayLabel: `${index + 1}日目`,
      events: dayEvents,
    };
  });
}

// ===== AsyncStorage 保存 =====

const TIMELINE_STORAGE_PREFIX = 'tripready_timeline_';

/**
 * カスタムイベントを保存
 */
export async function saveCustomEvents(tripId: string, events: TimelineEvent[]): Promise<void> {
  const customOnly = events.filter(e => !e.isAutoGenerated);
  await AsyncStorage.setItem(`${TIMELINE_STORAGE_PREFIX}${tripId}`, JSON.stringify(customOnly));
}

/**
 * カスタムイベントを読み込み
 */
export async function loadCustomEvents(tripId: string): Promise<TimelineEvent[]> {
  const raw = await AsyncStorage.getItem(`${TIMELINE_STORAGE_PREFIX}${tripId}`);
  return raw ? JSON.parse(raw) : [];
}

/**
 * 新しいカスタムイベントを作成
 */
export function createCustomEvent(
  tripId: string,
  date: string,
  time: string,
  type: TimelineEventType,
  title: string,
  options?: {
    endTime?: string;
    subtitle?: string;
    location?: string;
    address?: string;
    note?: string;
    guideKey?: string;
  },
): TimelineEvent {
  return {
    id: `custom_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    tripId,
    date,
    time,
    endTime: options?.endTime,
    type,
    title,
    subtitle: options?.subtitle,
    location: options?.location,
    address: options?.address,
    note: options?.note,
    guideKey: options?.guideKey,
    isAutoGenerated: false,
    completed: false,
  };
}

// ===== ユーティリティ =====

/**
 * 日付をフォーマット（3/28（土）形式）
 */
export function formatDateJa(dateStr: string): string {
  const d = new Date(dateStr);
  const days = ['日', '月', '火', '水', '木', '金', '土'];
  return `${d.getMonth() + 1}/${d.getDate()}（${days[d.getDay()]}）`;
}

/**
 * 時刻を表示用にフォーマット
 */
export function formatTime(time: string, endTime?: string): string {
  if (endTime) {
    return `${time} 〜 ${endTime}`;
  }
  return time;
}

/**
 * 旅程のサマリー情報を取得
 */
export function getTimelineSummary(schedules: DaySchedule[]): {
  totalDays: number;
  totalEvents: number;
  completedEvents: number;
  upcomingEvents: TimelineEvent[];
} {
  const allEvents = schedules.flatMap(s => s.events);
  const today = new Date().toISOString().slice(0, 10);
  const now = new Date().toTimeString().slice(0, 5);

  const upcoming = allEvents
    .filter(e => !e.completed && (e.date > today || (e.date === today && e.time >= now)))
    .slice(0, 3);

  return {
    totalDays: schedules.length,
    totalEvents: allEvents.length,
    completedEvents: allEvents.filter(e => e.completed).length,
    upcomingEvents: upcoming,
  };
}
