-- ============================================
-- TripReady: 外務省危険レベル 初期データ投入
-- 2026年3月時点の情報に基づく
-- Supabase SQL Editor で実行してください
-- ============================================

INSERT INTO mofa_danger_levels (country_code, mofa_country_code, country_name_ja, danger_level, danger_level_text, region_info, alerts, spot_info, source_url, fetched_at, updated_at)
VALUES
-- ===== レベル4: 退避勧告 =====
('IR', '0098', 'イラン', 4,
 'レベル4：退避してください。渡航は止めてください。',
 '[{"region":"全土","level":4,"text":"退避勧告"}]'::jsonb,
 ARRAY['全土にレベル4（退避勧告）が発出中','インターネット・国際電話が不安定','国際線フライトの減便・運航停止あり'],
 'イラン全土に退避勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0098.html',
 NOW(), NOW()),

('UA', '0380', 'ウクライナ', 4,
 'レベル4：退避してください。渡航は止めてください。',
 '[{"region":"全土","level":4,"text":"退避勧告"}]'::jsonb,
 ARRAY['全土にレベル4（退避勧告）が発出中','軍事侵攻が継続中'],
 'ウクライナ全土に退避勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0380.html',
 NOW(), NOW()),

('MM', '0095', 'ミャンマー', 4,
 'レベル4：退避してください。渡航は止めてください。',
 '[{"region":"全土","level":4,"text":"退避勧告"}]'::jsonb,
 ARRAY['全土にレベル4（退避勧告）が発出中','軍事クーデター後の情勢不安定'],
 'ミャンマー全土に退避勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0095.html',
 NOW(), NOW()),

('IL', '0972', 'イスラエル', 4,
 'レベル4：退避してください。渡航は止めてください。',
 '[{"region":"ガザ地区","level":4,"text":"退避勧告"},{"region":"ヨルダン川西岸","level":4,"text":"退避勧告"},{"region":"テルアビブ周辺","level":3,"text":"渡航中止勧告"}]'::jsonb,
 ARRAY['全土にレベル3〜4が発出中','ガザ・ヨルダン川西岸はレベル4'],
 'イスラエル全土に危険情報',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0972.html',
 NOW(), NOW()),

-- ===== レベル3: 渡航中止勧告（一部地域） =====
('RU', '0007', 'ロシア', 3,
 'レベル3：渡航は止めてください（渡航中止勧告）',
 '[{"region":"ウクライナ国境周辺","level":4,"text":"退避勧告"},{"region":"その他の地域","level":3,"text":"渡航中止勧告"}]'::jsonb,
 ARRAY['全土にレベル3（渡航中止勧告）以上','ウクライナ国境周辺はレベル4'],
 'ロシア全土に渡航中止勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0007.html',
 NOW(), NOW()),

-- ===== レベル2: 不要不急の渡航中止 =====
('PH', '0063', 'フィリピン', 2,
 'レベル2：不要不急の渡航は止めてください',
 '[{"region":"マニラ首都圏","level":1,"text":"十分注意"},{"region":"ミンダナオ島","level":3,"text":"渡航中止勧告"},{"region":"セブ・ボラカイ等","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['ミンダナオ島はレベル3','15歳未満の子供はWEG申請が必要'],
 'フィリピン・ミンダナオ島に渡航中止勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0063.html',
 NOW(), NOW()),

('IN', '0091', 'インド', 2,
 'レベル2：不要不急の渡航は止めてください',
 '[{"region":"カシミール地方","level":4,"text":"退避勧告"},{"region":"インド東北部","level":2,"text":"不要不急の渡航中止"},{"region":"デリー・ムンバイ等","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['カシミール地方はレベル4','e-Visa事前取得が必要'],
 'インド一部地域に危険情報',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0091.html',
 NOW(), NOW()),

('TR', '0090', 'トルコ', 2,
 'レベル2：不要不急の渡航は止めてください',
 '[{"region":"シリア・イラク国境地帯","level":4,"text":"退避勧告"},{"region":"南東部","level":3,"text":"渡航中止勧告"},{"region":"イスタンブール等","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['南東部国境地帯はレベル3〜4','イスタンブール・カッパドキア等は比較的安全'],
 'トルコ南東部に渡航中止勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0090.html',
 NOW(), NOW()),

('EG', '0020', 'エジプト', 2,
 'レベル2：不要不急の渡航は止めてください',
 '[{"region":"シナイ半島","level":3,"text":"渡航中止勧告"},{"region":"リビア国境地帯","level":3,"text":"渡航中止勧告"},{"region":"カイロ・ルクソール等","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['シナイ半島・リビア国境はレベル3','カイロ・ルクソール観光地はレベル1'],
 'エジプト一部地域に渡航中止勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0020.html',
 NOW(), NOW()),

('MX', '0052', 'メキシコ', 2,
 'レベル2：不要不急の渡航は止めてください',
 '[{"region":"チワワ州・タマウリパス州等","level":3,"text":"渡航中止勧告"},{"region":"カンクン・メキシコシティ","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['一部の州にレベル3（渡航中止勧告）','カンクン等観光地は比較的安全'],
 'メキシコ一部地域に渡航中止勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0052.html',
 NOW(), NOW()),

-- ===== レベル1: 十分注意 =====
('TH', '0066', 'タイ', 1,
 'レベル1：十分注意してください',
 '[{"region":"バンコク等","level":1,"text":"十分注意"},{"region":"南部国境県","level":3,"text":"渡航中止勧告"}]'::jsonb,
 ARRAY['南部国境県（パッタニー等）はレベル3','バンコク・チェンマイ等は比較的安全'],
 'タイ南部に渡航中止勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0066.html',
 NOW(), NOW()),

('KH', '0855', 'カンボジア', 1,
 'レベル1：十分注意してください',
 '[{"region":"プノンペン等","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['シェムリアップ（アンコールワット）は比較的安全','スリ・ひったくりに注意'],
 'カンボジア全土にレベル1',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0855.html',
 NOW(), NOW()),

('BR', '0055', 'ブラジル', 1,
 'レベル1：十分注意してください',
 '[{"region":"リオ・サンパウロ","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['大都市の治安に注意','スリ・強盗に要注意'],
 'ブラジル全土にレベル1',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0055.html',
 NOW(), NOW()),

('PE', '0051', 'ペルー', 1,
 'レベル1：十分注意してください',
 '[{"region":"リマ市内","level":1,"text":"十分注意"},{"region":"コカ栽培地域","level":2,"text":"不要不急の渡航中止"}]'::jsonb,
 ARRAY['マチュピチュ地域は安全','リマ市内は地区により治安が異なる'],
 'ペルー一部地域にレベル2',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0051.html',
 NOW(), NOW()),

('MA', '0212', 'モロッコ', 1,
 'レベル1：十分注意してください',
 '[{"region":"全土","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['マラケシュ旧市街はぼったくり注意','女性は控えめな服装推奨'],
 'モロッコ全土にレベル1',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0212.html',
 NOW(), NOW()),

-- ===== レベル0: 情報なし（安全な主要渡航先） =====
('KR', '0082', '韓国', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY['K-ETA免除中（変更の可能性あり）'],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0082.html',
 NOW(), NOW()),

('TW', '0886', '台湾', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY[]::text[],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0886.html',
 NOW(), NOW()),

('SG', '0065', 'シンガポール', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY[]::text[],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0065.html',
 NOW(), NOW()),

('US', '0001', 'アメリカ', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY['ESTA必須（渡航72時間前まで）'],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0001.html',
 NOW(), NOW()),

('AU', '0061', 'オーストラリア', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY[]::text[],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0061.html',
 NOW(), NOW()),

('FR', '0033', 'フランス', 1,
 'レベル1：十分注意してください',
 '[{"region":"パリ等","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['スリ・ひったくりに注意','パリ郊外は夜間外出を避ける'],
 'フランス全土にレベル1',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0033.html',
 NOW(), NOW()),

('GB', '0044', 'イギリス', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY['テロの脅威レベルは依然として高い'],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0044.html',
 NOW(), NOW()),

('DE', '0049', 'ドイツ', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY[]::text[],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0049.html',
 NOW(), NOW()),

('IT', '0039', 'イタリア', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY['スリ・ひったくりに注意'],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0039.html',
 NOW(), NOW()),

('ID', '0062', 'インドネシア', 1,
 'レベル1：十分注意してください',
 '[{"region":"バリ島等","level":1,"text":"十分注意"},{"region":"パプア州","level":2,"text":"不要不急の渡航中止"}]'::jsonb,
 ARRAY['VOA（到着ビザ）50万ルピア必要','バリ島は比較的安全'],
 'インドネシア一部地域にレベル2',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0062.html',
 NOW(), NOW()),

('VN', '0084', 'ベトナム', 0,
 '情報なし',
 '[]'::jsonb,
 ARRAY['ビザなし45日間','タクシーぼったくりに注意、Grabアプリ推奨'],
 '',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0084.html',
 NOW(), NOW()),

('MY', '0060', 'マレーシア', 0,
 '情報なし',
 '[{"region":"サバ州東海岸","level":2,"text":"不要不急の渡航中止"}]'::jsonb,
 ARRAY['サバ州東海岸はレベル2','クアラルンプールは治安良好'],
 'マレーシア一部地域にレベル2',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0060.html',
 NOW(), NOW()),

('SA', '0966', 'サウジアラビア', 1,
 'レベル1：十分注意してください',
 '[{"region":"全土","level":1,"text":"十分注意"},{"region":"イエメン国境地帯","level":3,"text":"渡航中止勧告"}]'::jsonb,
 ARRAY['イエメン国境地帯はレベル3','e-Visa事前取得が必要'],
 'サウジアラビア一部地域に渡航中止勧告',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0966.html',
 NOW(), NOW()),

('QA', '0974', 'カタール', 1,
 'レベル1：十分注意してください',
 '[{"region":"全土","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['中東情勢の緊迫化に伴い注意喚起'],
 'カタール全土にレベル1',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0974.html',
 NOW(), NOW()),

('AE', '0971', 'アラブ首長国連邦', 1,
 'レベル1：十分注意してください',
 '[{"region":"全土","level":1,"text":"十分注意"}]'::jsonb,
 ARRAY['中東情勢の緊迫化に伴い注意喚起','ドバイ・アブダビは治安良好'],
 'UAE全土にレベル1',
 'https://www.anzen.mofa.go.jp/info/pcinfectionspothazardinfo_0971.html',
 NOW(), NOW())

ON CONFLICT (country_code) DO UPDATE SET
  danger_level = EXCLUDED.danger_level,
  danger_level_text = EXCLUDED.danger_level_text,
  region_info = EXCLUDED.region_info,
  alerts = EXCLUDED.alerts,
  spot_info = EXCLUDED.spot_info,
  source_url = EXCLUDED.source_url,
  fetched_at = NOW(),
  updated_at = NOW();
